[package]
name = "grit"
version = "0.1.0"
authors = ["Josh Bechard <josh@oshbec.dev>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
uuid = { version = "0.7", features = ["v4", "serde"] }
sha1 = "0.6.0"
libflate = "0.1"
hex = "0.4.0"

[[bin]]
name = "grit-cli"
path = "src/bin/cli.rs"
